# Generated by Django 3.1.3 on 2020-12-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_free', models.BooleanField()),
            ],
        ),
    ]
