# Generated by Django 3.1.3 on 2020-12-13 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20201213_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messeger_1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='messeger_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
