# Generated by Django 3.1.3 on 2020-12-15 08:53

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201214_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image_url',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.upload_path),
        ),
    ]
